SELECT PLA0.CTACTB AS "Conta Contábil_ID" ,
       PLA0.DESCRCTA AS "Conta Contábil" ,
       PLA1.CTACTB AS "Conta Pai_ID",
       PLA1.DESCRCTA AS "Conta Pai" ,
       PLA2.CTACTB AS "Conta Avô_ID" ,
       PLA2.DESCRCTA AS "Conta Avô" ,
       PLA3.CTACTB AS "Conta Bisavô_ID" ,
       PLA3.DESCRCTA AS "Conta Bisavô" ,
       PLA4.CTACTB AS "Conta Tataravô_ID" ,
       PLA4.DESCRCTA AS "Conta Tataravô" ,
       PLA4.CTACTB AS "Conta Tetrâvo_ID" ,
       PLA4.DESCRCTA AS "Conta Tetrâvo"
FROM TCBPLA PLA0
LEFT JOIN TCBPLA PLA1 ON PLA0.CODCTACTBPAI = PLA1.CODCTACTB
LEFT JOIN TCBPLA PLA2 ON PLA1.CODCTACTBPAI = PLA2.CODCTACTB
LEFT JOIN TCBPLA PLA3 ON PLA2.CODCTACTBPAI = PLA3.CODCTACTB
LEFT JOIN TCBPLA PLA4 ON PLA3.CODCTACTBPAI = PLA4.CODCTACTB
LEFT JOIN TCBPLA PLA5 ON PLA4.CODCTACTBPAI = PLA5.CODCTACTB
WHERE PLA0.GRAU = (SELECT MAX(GRAU) FROM TCBPLA)
